UiPath/angular-components

.ci/templates/steps/create-bundle.yml, .ci/templates/steps/initialize-environment.yml, .ci/templates/steps/test.yml, azure-pipelines.yml, package.json
- extract task templates
- split testing and bundling into separate jobs
- generate build artifacts
=> CI / Extract Build Subtasks and Generate Build Artifacts

README.md, commitlint.config.js, package-lock.json, package.json
- configure conventional commit hooks
- configure commitizen
- add git guidelines to README
=> Commitizen + Husky + CommitLint + Conventional-Commits = 💖

.codeclimate.yml, projects/angular/components/src/ui-grid/managers/filter-manager.ts, projects/angular/components/src/ui-grid/managers/selection-manager.ts, projects/angular/directives/src/internal/ui-format.ts, projects/angular/directives/src/ui-dateformat/ui-dateformat.directive.ts, projects/angular/directives/src/ui-secondformat/ui-secondformat.directive.ts
- #23 
- #22
- #20
- #19
- #18 
- I've increased the line threshold to better suite our coding style, considering that we multi-line a lot to help with `merge conflicts`
=> Refactor to eliminate code smells and configure codeclimate

projects/angular/directives/src/ui-ng-let/ui-ng-let.directive.spec.ts, projects/angular/directives/src/ui-ng-let/ui-ng-let.directive.ts
- move embedded view creation into the `ctor`
=> Feature / Allow ngLet content to be queried statically

projects/angular/components/ui-grid/src/filters/ui-grid-dropdown-filter.directive.ts, projects/angular/components/ui-grid/src/filters/ui-grid-search-filter.directive.ts, projects/angular/components/ui-grid/src/ui-grid.component.html, projects/angular/components/ui-grid/src/ui-grid.component.spec.ts
You can now use a `[visible]` input on dropdown and search filters.
=> feat(grid): add ability to toggle filters visibility

projects/angular/components/ui-suggest/src/ui-suggest.component.html, projects/angular/components/ui-suggest/src/ui-suggest.component.scss, projects/angular/components/ui-suggest/src/ui-suggest.component.spec.ts, projects/angular/components/ui-suggest/src/ui-suggest.component.ts
- correctly scroll on keyboard navigation
- increase compat with standard / outline and fill mat form fields
- show only the desired tooltip on hover (item name / close)
Sandbox Test Branch: https://github.com/UiPath/angular-components/tree/ui-suggest-sandbox
=> fix / suggest component key-nav, tooltip and mat-form-field type compat

projects/angular/components/ui-suggest/src/ui-suggest.component.spec.ts, projects/angular/components/ui-suggest/src/ui-suggest.component.ts
=> feat(suggest): define fetch strategies

projects/angular/components/ui-grid/src/body/ui-grid-column.directive.spec.ts, projects/angular/components/ui-grid/src/body/ui-grid-column.directive.ts, projects/angular/components/ui-grid/src/components/ui-grid-toggle-columns/ui-grid-toggle-columns.component.html, projects/angular/components/ui-grid/src/components/ui-grid-toggle-columns/ui-grid-toggle-columns.component.scss, projects/angular/components/ui-grid/src/components/ui-grid-toggle-columns/ui-grid-toggle-columns.component.ts, projects/angular/components/ui-grid/src/components/ui-grid-toggle-columns/ui-grid-toggle-columns.module.ts, projects/angular/components/ui-grid/src/managers/index.ts, projects/angular/components/ui-grid/src/managers/resize/resize-manager.ts, projects/angular/components/ui-grid/src/managers/resize/types/resizableGrid.ts, projects/angular/components/ui-grid/src/managers/visibility-manager.ts, projects/angular/components/ui-grid/src/models/index.ts, projects/angular/components/ui-grid/src/models/visibleModel.ts, projects/angular/components/ui-grid/src/ui-grid.component.html, projects/angular/components/ui-grid/src/ui-grid.component.spec.ts, projects/angular/components/ui-grid/src/ui-grid.component.ts, projects/angular/components/ui-grid/src/ui-grid.intl.ts, projects/angular/components/ui-grid/src/ui-grid.module.ts
=> feat(grid): toggle columns - visibility manager

projects/angular/components/ui-grid/src/ui-grid.component.html, projects/angular/components/ui-grid/src/ui-grid.component.scss, projects/angular/components/ui-grid/src/ui-grid.component.spec.ts, projects/angular/components/ui-grid/src/ui-grid.component.ts
Grid: added key showHeaderButton to hide the column header for simple scenarios
Template :
=> feature / provide option for the grid to be without column header

CHANGELOG.md, package-lock.json, package.json, projects/angular/components/ui-grid/src/ui-grid.component.html, projects/angular/components/ui-grid/src/ui-grid.component.spec.ts, projects/angular/components/ui-grid/src/ui-grid.component.ts, projects/angular/components/ui-grid/src/ui-grid.module.ts, projects/angular/package.json
- remove previous workaround for the scroll problem in Firefox
- remove scroll compensation computation getter (TODO: backcompat ✔) and replace with a lazy observable
=> fix(grid): scroll performance

projects/angular/components/ui-suggest/src/ui-suggest.component.html, projects/angular/components/ui-suggest/src/ui-suggest.component.spec.ts, projects/angular/components/ui-suggest/src/ui-suggest.component.ts, projects/angular/components/ui-suggest/src/ui-suggest.intl.ts
=> feat(suggest): add support for minimum characters search

projects/angular/directives/ui-drag-and-drop-file/src/ui-drag-and-drop-file.directive.spec.ts, projects/angular/directives/ui-drag-and-drop-file/src/ui-drag-and-drop-file.directive.ts
- add support for multiple file types (closes #84)
- react to file type changes
- change file type checking to case-insensitive
=> feat(drag-and-drop-file): add multiple file types support

CHANGELOG.md, package-lock.json, package.json, projects/angular/components/ui-grid/src/ui-grid.component.html, projects/angular/components/ui-grid/src/ui-grid.component.spec.ts, projects/angular/components/ui-grid/src/ui-grid.component.ts, projects/angular/package.json
**CherryPick from [9.0.8](https://github.com/UiPath/angular-components/pull/103)**
=> fix(grid): multiple row selection with shift fix 🍒

package.json
Update publish config to be scoped to npm/gh registry
=> chore: update publish config to use scoped registry

projects/angular/components/ui-snackbar/src/ui-snackbar.component.spec.ts, projects/angular/components/ui-snackbar/src/ui-snackbar.component.ts
- add action support to `show` method
- improve unit tests
=> fix(snackbar): add action support to `show` method

projects/angular/directives/ui-scroll-into-view/src/ui-scroll-into-view.directive.ts
Added `block` input to `ui-scroll-into-view` directive to be able to configure it.
=> feat(scroll-into-view): add input to configure the block param

projects/angular/components/ui-grid/src/footer/ui-grid-footer.directive.ts, projects/angular/components/ui-grid/src/ui-grid.component.spec.ts
https://uipath.atlassian.net/browse/UI-40981
=> feat: expose page index setter

projects/angular/directives/ui-ng-let/src/ui-ng-let.directive.spec.ts, projects/angular/directives/ui-ng-let/src/ui-ng-let.directive.ts
Improved the typings for ngLet directive so we can benefit of intellisense when using it.
=> feat(ng-let): improve ngLet typings

package.json
- pre-requisites: update npm to v7 or later
=> build: update publish tasks to work with npm v7

CHANGELOG.md, package-lock.json, package.json, projects/angular/components/ui-suggest/src/_ui-suggest.theme.scss, projects/angular/components/ui-suggest/src/ui-suggest.component.html, projects/angular/components/ui-suggest/src/ui-suggest.component.spec.ts, projects/angular/package.json
=> fix(suggest): repair placeholder rendering 

CHANGELOG.md, package-lock.json, package.json, projects/angular/components/ui-suggest/src/ui-suggest.component.spec.ts, projects/angular/components/ui-suggest/src/ui-suggest.component.ts, projects/angular/package.json, projects/playground/src/app/pages/suggest/suggest.page.html
=> feat: suggest multiple custom

projects/angular/components/ui-grid/src/ui-grid.component.html, projects/angular/components/ui-grid/src/ui-grid.component.spec.ts
=> fix(grid): hide expanded filters if grid has custom filter [OR-58619]

CHANGELOG.md, package-lock.json, package.json, projects/angular/components/ui-grid/src/ui-grid.component.html, projects/angular/components/ui-grid/src/ui-grid.component.spec.ts, projects/angular/components/ui-grid/src/ui-grid.component.ts, projects/angular/package.json
=> fix(grid): unselect grid header checbox if data changes [OR-56382]

CHANGELOG.md, package-lock.json, package.json, projects/angular/components/ui-grid/src/filters/ui-grid-search-filter.directive.ts, projects/angular/components/ui-grid/src/managers/filter-manager.spec.ts, projects/angular/components/ui-grid/src/ui-grid.component.html, projects/angular/components/ui-grid/src/ui-grid.component.ts, projects/angular/package.json
* clear selection on single mode search grid filter
* de-highlight filter column on multiple mode search grid filter when all options are deselected
=> fix(grid): search grid filter

CHANGELOG.md, package-lock.json, package.json, projects/angular/components/ui-suggest/src/ui-suggest.component.html, projects/angular/components/ui-suggest/src/ui-suggest.component.scss, projects/angular/components/ui-suggest/src/ui-suggest.component.spec.ts, projects/angular/components/ui-suggest/src/ui-suggest.component.ts, projects/angular/components/ui-suggest/src/utils/items.utils.ts, projects/angular/package.json, projects/playground/src/app/app.component.scss, projects/playground/src/app/pages/suggest/suggest.page.html, projects/playground/src/app/pages/suggest/suggest.page.scss, projects/playground/src/app/pages/suggest/suggest.page.ts
=> feat(suggest): add support lazy mode

CHANGELOG.md, package-lock.json, package.json, projects/angular/components/ui-grid/src/managers/filter-manager.ts, projects/angular/components/ui-grid/src/managers/sort-manager.ts, projects/angular/components/ui-grid/src/ui-grid.component.spec.ts, projects/angular/components/ui-grid/src/ui-grid.component.ts, projects/angular/package.json
* clear search, filters and sorting on action and emit an event to notify user, so they can process the operation
=> feat(grid): reset search, filters and sorting on action

CHANGELOG.md, package-lock.json, package.json, projects/angular/components/ui-grid/src/ui-grid.component.scss, projects/angular/package.json
Add spacing between the grid's rhs action buttons.
=> fix(grid): main action buttons spacing

CHANGELOG.md, package-lock.json, package.json, projects/angular/components/ui-suggest/src/ui-suggest.component.html, projects/angular/components/ui-suggest/src/ui-suggest.component.scss, projects/angular/components/ui-suggest/src/ui-suggest.component.spec.ts, projects/angular/package.json, version-bump.js
Adds support for icons in chips.
=> feat(suggest): add icons on chips

projects/angular/components/ui-suggest/src/ui-suggest.component.scss
**Description**
Small scss change
=> feat(suggest): update styling

CHANGELOG.md, package-lock.json, package.json, projects/angular/components/ui-suggest/src/ui-suggest.component.html, projects/angular/package.json
https://github.com/UiPath/angular-components/assets/12661929/c2ba3497-043b-499d-aec3-67d384a0a2f4
=> fix(suggest): add aria-selected to item

projects/angular/components/ui-grid/src/components/ui-grid-toggle-columns/ui-grid-toggle-columns.component.html
Makes columns reset button accessible by keyboard.
https://uipath.atlassian.net/browse/PLT-35789
=> Fix: columns reset button a11y

projects/angular/components/ui-grid/src/components/ui-grid-toggle-columns/ui-grid-toggle-columns.component.html, projects/angular/components/ui-grid/src/components/ui-grid-toggle-columns/ui-grid-toggle-columns.component.scss, projects/angular/components/ui-grid/src/components/ui-grid-toggle-columns/ui-grid-toggle-columns.component.ts, projects/angular/components/ui-grid/src/models/dataModel.ts, projects/angular/components/ui-grid/src/ui-grid.component.html, projects/angular/components/ui-grid/src/ui-grid.component.scss, projects/angular/components/ui-grid/src/ui-grid.component.spec.ts, projects/angular/components/ui-grid/src/ui-grid.component.ts, projects/playground/src/app/pages/grid/component/grid.component.html, projects/playground/src/app/pages/grid/grid.models.ts, projects/playground/src/app/pages/grid/grid.page.ts, projects/playground/src/app/utils/settings-store.ts
- implement `SettingsStore` to persist playground configured settings
- drop `useLegacy` flag
[OR-68404](https://uipath.atlassian.net/browse/OR-68404)
[OR-68404]: https://uipath.atlassian.net/browse/OR-68404?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Chore/use legacy cleanup [OR-68404]

projects/angular/components/ui-grid/src/_ui-grid.theme.scss, projects/angular/components/ui-grid/src/managers/resize/resize-manager.ts, projects/angular/components/ui-grid/src/ui-grid.component.html, projects/angular/components/ui-grid/src/ui-grid.component.scss, projects/angular/components/ui-grid/src/ui-grid.component.ts, projects/playground/src/app/pages/grid/grid.page.ts
Show colored border for column resize instead of a drag icon.
https://uipath.atlassian.net/browse/PLT-29993
=> feat(grid): show border for column resize

CHANGELOG.md, package-lock.json, package.json, projects/angular/components/ui-suggest/src/models/suggestValue.ts, projects/angular/components/ui-suggest/src/ui-suggest.component.html, projects/angular/components/ui-suggest/src/ui-suggest.component.spec.ts, projects/angular/components/ui-suggest/src/ui-suggest.component.ts, projects/angular/package.json
Adds custom tooltip to ui-suggest (in case you want to show something different in certain scenarios than the text).
=> feat(suggest): add custom tooltip

projects/angular/components/ui-grid/src/ui-grid.component.spec.ts, projects/angular/components/ui-grid/src/ui-grid.component.ts
- remove tooltip from currently selected radio button
=> Fix(grid): remove tooltip on selected radio button

CHANGELOG.md, package-lock.json, package.json, projects/angular/components/ui-suggest/src/ui-suggest.component.html, projects/angular/components/ui-suggest/src/ui-suggest.component.ts, projects/angular/components/ui-suggest/src/ui-suggest.mat-form-field.ts, projects/angular/package.json
Reduce the height of ui-suggest when no results are found and customItemSize is used.
https://uipath.atlassian.net/browse/OR-65722
=> 🍒 fix(suggest): reduce height of ui-suggest when no results found

CHANGELOG.md, package-lock.json, package.json, projects/angular/components/ui-grid/src/_ui-grid.theme.scss, projects/angular/components/ui-grid/src/managers/resize/resize-manager.ts, projects/angular/components/ui-grid/src/ui-grid.component.html, projects/angular/components/ui-grid/src/ui-grid.component.scss, projects/angular/components/ui-grid/src/ui-grid.component.ts, projects/angular/package.json, projects/playground/src/app/pages/grid/grid.page.ts
Show colored border for column resize instead of a drag icon.
https://uipath.atlassian.net/browse/PLT-29993
It is a prerequisite for the horizontally scrollable grid feature.
=> 🍒 feat(grid): show border for column resize

CHANGELOG.md, package-lock.json, package.json, projects/angular/components/ui-grid/src/ui-grid.component.html, projects/angular/package.json
=> fix(grid): don't replace main action buttons on row selection

CHANGELOG.md, package-lock.json, package.json, projects/angular/components/ui-grid/src/_ui-grid-variables.scss, projects/angular/components/ui-grid/src/_ui-grid.theme.scss, projects/angular/components/ui-grid/src/body/ui-grid-column.directive.ts, projects/angular/components/ui-grid/src/managers/resize/resize-manager.constants.ts, projects/angular/components/ui-grid/src/managers/resize/resize-manager.factory.ts, projects/angular/components/ui-grid/src/managers/resize/resize-manager.ts, projects/angular/components/ui-grid/src/managers/resize/strategies/index.ts, projects/angular/components/ui-grid/src/managers/resize/strategies/scrollable-grid-resizer.ts, projects/angular/components/ui-grid/src/managers/resize/types/resizeStrategy.ts, projects/angular/components/ui-grid/src/models/dataModel.ts, projects/angular/components/ui-grid/src/ui-grid.component.html, projects/angular/components/ui-grid/src/ui-grid.component.scss, projects/angular/components/ui-grid/src/ui-grid.component.spec.ts, projects/angular/components/ui-grid/src/ui-grid.component.ts, projects/angular/package.json, projects/playground/src/app/pages/grid/component/grid.component.html, projects/playground/src/app/pages/grid/component/grid.component.ts, projects/playground/src/app/pages/grid/grid.models.ts, projects/playground/src/app/pages/grid/grid.page.ts
Todo:
To be addressed in a future PR
Tracking the remaining work in Jira
=> Feat(grid): horizontal scroll

CHANGELOG.md, package-lock.json, package.json, projects/angular/components/ui-grid/src/_ui-grid.theme.scss, projects/angular/components/ui-grid/src/ui-grid.component.ts, projects/angular/package.json
although the min-width is the same, the container's width may have changed
=> Fix(grid): reemit min-width value on grid container width changes

CHANGELOG.md, package-lock.json, package.json, projects/angular/components/ui-grid/src/_ui-grid.theme.scss, projects/angular/components/ui-grid/src/body/ui-grid-column.directive.ts, projects/angular/components/ui-grid/src/managers/resize/resize-manager.constants.ts, projects/angular/components/ui-grid/src/managers/resize/resize-manager.ts, projects/angular/components/ui-grid/src/managers/resize/strategies/scrollable-grid-resizer.ts, projects/angular/components/ui-grid/src/ui-grid.component.html, projects/angular/components/ui-grid/src/ui-grid.component.scss, projects/angular/components/ui-grid/src/ui-grid.component.spec.ts, projects/angular/components/ui-grid/src/ui-grid.component.ts, projects/angular/package.json
=> Fix(grid): limit sticky columns max width  

CHANGELOG.md, package-lock.json, package.json, projects/angular/components/ui-grid/src/managers/resize/resize-manager.constants.ts, projects/angular/components/ui-grid/src/managers/resize/strategies/scrollable-grid-resizer.ts, projects/angular/components/ui-grid/src/ui-grid.component.html, projects/angular/components/ui-grid/src/ui-grid.component.scss, projects/angular/components/ui-grid/src/ui-grid.component.spec.ts, projects/angular/components/ui-grid/src/ui-grid.component.ts, projects/angular/package.json
works only with scrollable resize strategy
=> Feat: min grid width input for scrollable strategy

CHANGELOG.md, package-lock.json, package.json, projects/angular/components/ui-grid/src/components/ui-grid-toggle-columns/ui-grid-toggle-columns.component.html, projects/angular/components/ui-grid/src/components/ui-grid-toggle-columns/ui-grid-toggle-columns.component.scss, projects/angular/components/ui-snackbar/src/_ui-snackbar.theme.scss, projects/angular/package.json
- apply correctly the background color to the snackbar
- display grid toggle columns dropdown header in a single line
=> fix: material styles

projects/angular/components/ui-suggest/src/ui-suggest.component.spec.ts, projects/angular/components/ui-suggest/src/ui-suggest.component.ts, projects/angular/components/ui-suggest/src/utils/items.utils.ts
[SOL-1407](https://uipath.atlassian.net/browse/SOL-1407)
[SOL-1407]: https://uipath.atlassian.net/browse/SOL-1407?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: lazy suggest buffer size

projects/angular/components/ui-file-picker/src/file-drop-zone/file-drop-zone.component.html, projects/angular/components/ui-file-picker/src/file-drop-zone/file-drop-zone.component.spec.ts, projects/angular/components/ui-file-picker/src/file-drop-zone/file-drop-zone.component.ts
Add the ability to make any element a drag-and-drop files zone without having an HTML input element behind
=> feat(file-picker): make input optional in file drop zone

CHANGELOG.md, package-lock.json, package.json, projects/angular/components/ui-grid/src/_ui-grid-variables.scss, projects/angular/components/ui-grid/src/_ui-grid.theme.scss, projects/angular/components/ui-grid/src/ui-grid.component.scss, projects/angular/package.json
[Figma](https://www.figma.com/file/l1I5dUQFDxqPYo322wEpXx/Apollo-components-(web)?type=design&node-id=401-28&mode=design&t=iL3Aq7ghIUQD2PHs-0)
Changes the hover color for the rows.
=> fix(grid): adapt to apollo design 

CHANGELOG.md, package-lock.json, package.json, projects/angular/components/ui-grid/src/managers/resize/resize-manager.ts, projects/angular/components/ui-grid/src/ui-grid.component.html, projects/angular/components/ui-grid/src/ui-grid.component.scss, projects/angular/components/ui-grid/src/ui-grid.component.ts, projects/angular/package.json
- Fixing the grid loading bar jump
- Centering empty state of scrollable grid
=> Fix(scrollable-grid): styling fixes 

CHANGELOG.md, package-lock.json, package.json, projects/angular/components/ui-grid/src/filters/ui-grid-dropdown-filter.directive.ts, projects/angular/components/ui-grid/src/managers/data-manager.ts, projects/angular/components/ui-grid/src/managers/filter-manager.ts, projects/angular/components/ui-grid/src/ui-grid.component.html, projects/angular/components/ui-grid/src/ui-grid.component.scss, projects/angular/components/ui-grid/src/ui-grid.component.spec.ts, projects/angular/components/ui-grid/src/ui-grid.component.ts, projects/angular/components/ui-suggest/src/ui-suggest.component.ts, projects/angular/directives/keyboard-shortcut/src/keyboard-shortcut.directive.ts, projects/angular/package.json
- setting `ignoreUnknown` to avoid [unknown type error](https://portal.azure.com/#view/AppInsightsExtension/DetailsV2Blade/ComponentId~/%7B%22SubscriptionId%22%3A%222b954974-d5db-416f-a230-f81cb168de8a%22%2C%22ResourceGroup%22%3A%22crpa-prod-orch-ne-rg%22%2C%22Name%22%3A%22crpa-prod-orch-global-appinsights%22%2C%22LinkedApplicationType%22%3A0%2C%22ResourceId%22%3A%22%252Fsubscriptions%252F2b954974-d5db-416f-a230-f81cb168de8a%252FresourceGroups%252Fcrpa-prod-orch-ne-rg%252Fproviders%252FMicrosoft.Insights%252Fcomponents%252Fcrpa-prod-orch-global-appinsights%22%2C%22ResourceType%22%3A%22microsoft.insights%252Fcomponents%22%2C%22IsAzureFirst%22%3Afalse%7D/DataModel~/%7B%22eventId%22%3A%22a1f47e45-88db-11ee-8bc4-000d3ab86027%22%2C%22timestamp%22%3A%222023-11-22T02%3A04%3A59.057Z%22%2C%22cacheI …
=> fix(grid): multi selection filter

projects/angular/components/ui-grid/src/ui-grid.component.scss, projects/angular/components/ui-grid/src/ui-grid.component.spec.ts
https://uipath.atlassian.net/browse/OR-75788
=> feat(grid): increase header row height in high density mode

package-lock.json, package.json, projects/angular/components/ui-tree-select/src/ui-tree-select.component.html, projects/angular/components/ui-tree-select/src/ui-tree-select.component.scss, projects/angular/package.json
[SOL-2218](https://uipath.atlassian.net/browse/SOL-2218)
[SOL-2218]: https://uipath.atlassian.net/browse/SOL-2218?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(ui-tree-select): focus-visible state

projects/angular/components/ui-grid/src/ui-grid.component.scss
https://uipath.atlassian.net/browse/OR-76287
=> feat(grid): update font and icon sizes for high density mode

CHANGELOG.md, package-lock.json, package.json, projects/angular/components/ui-grid/src/ui-grid.component.html, projects/angular/components/ui-grid/src/ui-grid.component.ts, projects/angular/package.json, projects/playground/src/app/pages/grid/component/grid.component.html, projects/playground/src/app/pages/grid/grid.models.ts, projects/playground/src/app/pages/grid/grid.page.ts
https://github.com/UiPath/angular-components/assets/51370844/e96f5484-f233-49c6-854c-50c872819442
=> feat(grid): allow swapping filter containers
