UiPath/angular-components

projects/angular/components/ui-suggest/src/ui-suggest.component.ts

- on set disabled replace detectChanges w markForCheck
- in case the viewRef has been destroyed detectChanges throws error, we should just mark for check

fix(suggest):  set disabled markForCheck

---

projects/angular/components/ui-grid/src/header/ui-grid-header-button.directive.ts
projects/angular/components/ui-grid/src/header/ui-grid-header.directive.ts
projects/angular/components/ui-grid/src/ui-grid.component.html
projects/angular/components/ui-grid/src/ui-grid.component.spec.ts

```html
<ui-header-button type="inline">
<ng-template>
<ng-container *ngIf="hasCustomFilters$ | async">
<mat-divider class="ui-grid-reset-divider" vertical="true"></mat-divider>
<button (click)="resetFilter()"
class="ui-grid-button-reset"
mat-button
color="primary">
<span translate>reset_to_defaults</span>
</button>
</ng-container>
</ng-template>
</ui-header-button>
```

feat(grid): define inline header buttons

---

projects/angular/components/ui-suggest/src/ui-suggest.component.html

workaround for https://github.com/angular/components/issues/15648
this is a fix for the case when the tooltip gets 'hanged' after closing the virtual scrolled list

fix(suggest): remove tooltip after selection

---

projects/angular/components/ui-snackbar/src/ui-snackbar.component.spec.ts
projects/angular/components/ui-snackbar/src/ui-snackbar.component.ts

`MatSnackBar` accepts zero as duration which means that the snack bar will not be hidden.
This PR modifies `UiSnackBarService` to have the same behavior.
- using `UiSnackBarService`, open a snackbar using zero as duration
expected: the snackbar should stay on screen indefinitely

feat(snackbar): allow zero as duration

---

CHANGELOG.md
package-lock.json
package.json
projects/angular/components/ui-grid/src/ui-grid.component.html
projects/angular/components/ui-grid/src/ui-grid.component.ts
projects/angular/components/ui-grid/src/ui-grid.module.ts
projects/angular/package.json

Since ng 9 upgrade, on firefox, the cdk-virtual-scroll-viewport has scrolling issues (in our setup). If you scroll with the mouse wheel, it keeps doing translateY too early and resets the user position. If autosize is removed, this issue isn't reproduced anymore (there are still some small early translations in some conditions, but you can scroll to the bottom). 
We should use the autosize (cdk/experimental) when it's ready for production and out of experimental. Untill then you can pass the itemSize as an input prop.

fix(grid): remove cdk experimental (issues with scrolling on firefox)

---

projects/angular/directives/ui-secondformat/src/ui-secondformat.directive.spec.ts
projects/angular/directives/ui-secondformat/src/ui-secondformat.directive.ts
projects/angular/directives/ui-secondformat/src/ui-secondformat.module.ts

it looks like the old implementation had a problem with languages other than English (e.g. German doesn't have 'mm' or 'hh' for relative times).
the new implementation uses moment's `duration()` with `humanize()` and a tooltip with `toIsoString()`
although the new implementation is a Component, it is backward compatible with the Directive and will be moved in its correct folder in v10.

fix(secondformat): change behavior to average & ISO8601

---

projects/angular/components/ui-grid/src/managers/visibility-manager.ts

Production build were missing a key piece of functionality – disable toggling at least one column.
TBD how we avoid that in the future

fix(grid): default toggle disabled column

---

CHANGELOG.md
package-lock.json
package.json
projects/angular/components/ui-snackbar/src/public_api.ts
projects/angular/components/ui-snackbar/src/ui-snackbar.component.spec.ts
projects/angular/components/ui-snackbar/src/ui-snackbar.component.ts
projects/angular/package.json

add support for injecting `UI_MAT_SNACK_BAR_DEFAULT_OPTIONS` which can enable `restrictHtml` - stripping the html tags and leaving only the text content in the shown message

feat(snackbar): add optional hardening when showing messages

---

CHANGELOG.md
package-lock.json
package.json
projects/angular/components/ui-grid/src/ui-grid.component.html
projects/angular/components/ui-grid/src/ui-grid.component.spec.ts
projects/angular/components/ui-grid/src/ui-grid.component.ts
projects/angular/package.json

When shift key is used while multi selecting, the checkbox appeared as unselected even though in the model it was selected.
Performance improvements for shift selection algorithm (instead of deselecting everything and selecting again, we calculate the rows to be selected and the rows to be deselected excepting the ones that already are in correct state).

fix(grid): multiple row selection with shift fix

---

CHANGELOG.md
package-lock.json
package.json
projects/angular/components/ui-grid/src/components/ui-grid-search/ui-grid-search.component.html
projects/angular/components/ui-grid/src/managers/sort-manager.spec.ts
projects/angular/components/ui-grid/src/managers/sort-manager.ts
projects/angular/components/ui-grid/src/models/sortModel.ts
projects/angular/components/ui-grid/src/ui-grid.component.html
projects/angular/components/ui-grid/src/ui-grid.component.spec.ts
projects/angular/components/ui-grid/src/ui-grid.component.ts
projects/angular/components/ui-grid/src/ui-grid.intl.ts
projects/angular/package.json

fix(a11y): grid announce

---

projects/angular/a11y/src/ui-auto-accessible-label/ui-auto-accessible-label.directive.ts

Add support for auto-adding aria-label based on matTooltip to mat-icons that have tabindex.

fix(a11y): add mat-icon[tabindex] to auto-accessible-label directive

---

CHANGELOG.md
package-lock.json
package.json
projects/angular/components/ui-grid/src/body/ui-grid-column.directive.spec.ts
projects/angular/components/ui-grid/src/body/ui-grid-column.directive.ts
projects/angular/components/ui-grid/src/managers/selection-manager.spec.ts
projects/angular/components/ui-grid/src/managers/selection-manager.ts
projects/angular/components/ui-grid/src/ui-grid.component.html
projects/angular/components/ui-grid/src/ui-grid.component.spec.ts
projects/angular/components/ui-grid/src/ui-grid.component.ts
projects/angular/components/ui-grid/src/ui-grid.intl.ts
projects/angular/directives/ui-drag-and-drop-file/src/ui-drag-and-drop-file.directive.spec.ts
projects/angular/directives/ui-drag-and-drop-file/src/ui-drag-and-drop-file.directive.ts
projects/angular/package.json
projects/angular/testing/src/utilities/event-generator.ts

- the user is announced of the change and he can also press `Shift + ALT + Arrow Up` to navigate straight to the newly revealed actions

fix: a11y grid 

---

projects/angular/components/ui-grid/src/ui-grid.component.html

by default a button within a form has a type="submit" which triggers form submission

fix(grid): add type="button" to filter button

---

CHANGELOG.md
package-lock.json
package.json
projects/angular/components/ui-suggest/src/ui-suggest.component.ts
projects/angular/package.json

consumers may use this to reset/refetch items even if closed in order to trigger validations

feat(suggest): expose input to allow fetching while closed

---

CHANGELOG.md
package-lock.json
package.json
projects/angular/components/ui-grid/src/filters/ui-grid-dropdown-filter.directive.ts
projects/angular/components/ui-grid/src/managers/filter-manager.ts
projects/angular/components/ui-grid/src/ui-grid.component.html
projects/angular/components/ui-grid/src/ui-grid.component.spec.ts
projects/angular/package.json

Create optional input `emptyValue` for `UiGridDropdownFilterDirective` in order to clearly count the applied filters of the grid

feat(grid): add filters empty state input

---

CHANGELOG.md
package-lock.json
package.json
projects/angular/components/ui-grid/src/components/ui-grid-toggle-columns/ui-grid-toggle-columns.component.html
projects/angular/components/ui-grid/src/components/ui-grid-toggle-columns/ui-grid-toggle-columns.component.scss
projects/angular/package.json

1. set divider height 32px
2. change icon of column button with `table_chart` icon from material
3. add an arrow for column button

chore(grid): change column icon and divider height

---

CHANGELOG.md
package-lock.json
package.json
projects/angular/components/ui-grid/src/managers/filter-manager.ts
projects/angular/components/ui-grid/src/ui-grid.component.html
projects/angular/components/ui-grid/src/ui-grid.component.spec.ts
projects/angular/components/ui-grid/src/ui-grid.component.ts
projects/angular/components/ui-grid/src/ui-grid.intl.ts
projects/angular/package.json
projects/angular/testing/src/utilities/fake-file-list.ts
projects/playground/src/app/pages/grid/component/grid.component.html
projects/playground/src/app/pages/grid/component/grid.component.ts
projects/playground/src/app/pages/grid/grid.models.ts
projects/playground/src/app/pages/grid/grid.page.ts
tsconfig.json

Creating a new input called `customFilterValue` which takes precedence over the usual filters. 
The output `removeCustomFilter` emits after pressing the "Clear custom filter"  button, then the custom filter is gone, and the usual filters are applied.

Feat: grid custom filter value

---

projects/angular/components/ui-suggest/src/ui-suggest.component.html
projects/angular/components/ui-suggest/src/ui-suggest.component.scss
projects/angular/components/ui-suggest/src/ui-suggest.component.spec.ts
projects/angular/components/ui-suggest/src/ui-suggest.component.ts
projects/playground/src/app/pages/suggest/suggest.page.html

Added a compact mode in order to display the multiselect summary as an alternative to chips
Solves: https://uipath.atlassian.net/browse/ACTV-15373

feat(suggest): add compact summary support

---

projects/angular/components/ui-grid/src/ui-grid.component.html
projects/angular/components/ui-grid/src/ui-grid.component.ts

OR-58318
---
Display toggle columns divider if the grid has filters or custom filter
Before change:
After change:

fix(grid): add toggle columns divider [OR-58318]

---

CHANGELOG.md
package-lock.json
package.json
projects/angular/components/ui-grid/src/_ui-grid.theme.scss
projects/angular/components/ui-grid/src/body/ui-grid-column.directive.ts
projects/angular/components/ui-grid/src/ui-grid.component.html
projects/angular/components/ui-grid/src/ui-grid.component.spec.ts
projects/angular/package.json

Add `aria-label` to column headers in order to improve a11y.
Add new input `description` to `ui-grid-column` directive which inserts an info icon in the column header with the text in tooltip.

feat(grid): add column description icon

---

CHANGELOG.md
package-lock.json
package.json
projects/angular/directives/ui-dateformat/src/ui-dateformat.directive.ts
projects/angular/package.json

It is necessary to trigger a change detection when setting the `date` input in order to display the `matTooltip` on hovering

fix(dateformat): trigger change detection on setting input

---

projects/angular/components/ui-grid/src/body/ui-grid-column.directive.ts
projects/angular/components/ui-grid/src/managers/filter-manager.ts
projects/angular/components/ui-grid/src/managers/sort-manager.spec.ts
projects/angular/components/ui-grid/src/managers/sort-manager.ts

Adding a new input `referenceProperty` to `UiGridColumnDirective` that takes precedence over `property` when sorting and filtering

feat(grid): add new input queryProperty to UiGridColumnDirective 

---

projects/angular/components/ui-grid/src/_ui-grid.theme.scss
projects/angular/components/ui-grid/src/ui-grid.component.html
projects/angular/components/ui-grid/src/ui-grid.component.scss
projects/angular/components/ui-grid/src/ui-grid.component.spec.ts
projects/angular/components/ui-grid/src/ui-grid.component.ts
projects/playground/src/app/pages/grid/component/grid.component.html

adds support for multiple expanded rows

feat(grid): multiple expanded rows

---

projects/angular/components/ui-suggest/src/models/suggestValue.ts
projects/angular/components/ui-suggest/src/ui-suggest.component.html
projects/angular/components/ui-suggest/src/ui-suggest.component.spec.ts
projects/angular/components/ui-suggest/src/ui-suggest.component.ts

1. Add a `disabled` flag to ISuggestValue in order to allow users the possibility to disable items
2. Add the input `displayValueFactory` which will be used both to display the summary and the tooltip for the input. It defaults to `array.join(', ')`

feat(suggest): add a `disabled` flag to ISuggestValue & `displayValueFactory` input

---

CHANGELOG.md
package-lock.json
package.json
projects/angular/directives/ui-dateformat/src/ui-dateformat.directive.spec.ts
projects/angular/directives/ui-dateformat/src/ui-dateformat.directive.ts
projects/angular/package.json

markForCheck is needed so that changes propagate to matTooltip

fix(dateformat): call markForCheck only on initial assignment

---

CHANGELOG.md
package-lock.json
package.json
projects/angular/directives/keyboard-shortcut/src/keyboard-shortcut.directive.spec.ts
projects/angular/directives/keyboard-shortcut/src/keyboard-shortcut.directive.ts
projects/angular/package.json

when all the required keys for a shortcut are pressed simultaneously an event is emitted and the key pressed state is reset

Fix(keyboard-shortcut): require keys to be pressed again in order to emit again

---

CHANGELOG.md
package-lock.json
package.json
projects/angular/directives/ui-dateformat/src/ui-dateformat.directive.ts
projects/angular/package.json

Fixes some default formatting issues:
- Absolute time tooltip now contains seconds
- Relatve time tooltip is now correctly using Luxon

fix: luxon formatting in tooltips

---

CHANGELOG.md
package-lock.json
package.json
projects/angular/directives/ui-dateformat/src/ui-dateformat.directive.ts
projects/angular/package.json

When computing absolute time, if `luxon` was enabled and `dateFormat` was a `string`, we would still use `moment`.

fix: dateformat luxon absolute time

---

CHANGELOG.md
package-lock.json
package.json
projects/angular/components/ui-grid/src/ui-grid.component.html
projects/angular/components/ui-grid/src/ui-grid.component.scss
projects/angular/components/ui-grid/src/ui-grid.component.spec.ts
projects/angular/components/ui-grid/src/ui-grid.component.ts
projects/angular/package.json

When the column header is focused it should display a tooltip that consists of the concatenation of column title and column description.
Demo: 
https://user-images.githubusercontent.com/87014385/222734741-12d3ef1b-e2c2-4f30-9337-0d36b061baab.mp4

Fix: display concatenated tooltip (title + description) on keyboard focus

---

CHANGELOG.md
package-lock.json
package.json
projects/angular/directives/ui-dateformat/src/ui-dateformat.directive.ts
projects/angular/directives/ui-secondformat/src/ui-secondformat.directive.luxon.spec.ts
projects/angular/directives/ui-secondformat/src/ui-secondformat.directive.ts
projects/angular/package.json

Dropped `humanize-duration`, as it doesn't handle all our supported locales.
For our specific case here, we can rely on luxon only, by finding the largest unit of the duration, creating a new one from it and then calling `toHuman`.
If we don't search for the largest unit, luxon would return all units in the humanized string.

[v14.5] fix: humanize duration in different locales

---

projects/angular/components/ui-grid/src/ui-grid.component.scss
projects/angular/components/ui-suggest/src/ui-suggest.component.html
projects/angular/components/ui-suggest/src/ui-suggest.component.spec.ts
projects/angular/components/ui-suggest/src/ui-suggest.component.ts

**Description**
Now the focus will go to the next element when the user press the TAB key.
Minor change: changed the style for the grid
**JIRA**
[ACTV-63316](https://uipath.atlassian.net/browse/ACTV-63316)
[ACTV-63441](https://uipath.atlassian.net/browse/ACTV-63441)
[ACTV-63316]: https://uipath.atlassian.net/browse/ACTV-63316?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ACTV-63441]: https://uipath.atlassian.net/browse/ACTV-63441?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(suggest): fix focus logic when navigating with TAB

---

CHANGELOG.md
package-lock.json
package.json
projects/angular/components/ui-suggest/src/ui-suggest.component.ts
projects/angular/package.json
projects/playground/src/app/pages/suggest/suggest.module.ts
projects/playground/src/app/pages/suggest/suggest.page.html
projects/playground/src/app/pages/suggest/suggest.page.ts

**Description**
Added itemSelected output because it is very useful when we use `custom template`. We can use this output to detect when a item is selected and use that event in the logic of the custom template.
I created an example in the `suggest page` where I implemented a suggest component that uses radio-buttons.

fix(suggest): add item selected output event

---

CHANGELOG.md
package-lock.json
package.json
projects/angular/components/ui-suggest/src/ui-suggest.component.ts
projects/angular/package.json

`this.debounceTime` is used in the constructor, although it is an input, so we need to move the logic that uses it in `ngOnInit`, otherwise its default is always used instead.

fix(suggest): use debounceTime input after it is set

---

CHANGELOG.md
package-lock.json
package.json
projects/angular/components/ui-grid/src/filters/ui-grid-search-filter.directive.ts
projects/angular/components/ui-grid/src/ui-grid.component.spec.ts
projects/angular/package.json

In case we pass in a default value for multiple filters, they get duplicated (this breaks the react wrapper that we did).

fix(grid): search filters initial value

---

CHANGELOG.md
package-lock.json
package.json
projects/angular/components/ui-grid/src/ui-grid.component.html
projects/angular/package.json
projects/playground/src/app/pages/grid/component/grid.component.html

Add role="row" to card wrapper. Remove tabindex="0" from card wrapper. 
The card view template is now responsible for settings role="gridcell" and focus

fix(a11y): certain aria roles must contain particular children in grid

---

CHANGELOG.md
projects/angular/components/ui-grid/src/ui-grid.component.html
projects/angular/components/ui-grid/src/ui-grid.component.scss

Use an arrow cursor instead of text select cursor on headers of columns which are not sortable.
https://uipath.atlassian.net/browse/PLT-29992

fix(grid): use arrow cursor on column header

---

CHANGELOG.md
package-lock.json
package.json
projects/angular/components/ui-suggest/src/models/suggestValue.ts
projects/angular/components/ui-suggest/src/ui-suggest.component.html
projects/angular/components/ui-suggest/src/ui-suggest.component.spec.ts
projects/angular/components/ui-suggest/src/ui-suggest.component.ts
projects/angular/package.json

🍒 https://github.com/UiPath/angular-components/pull/383

feat(suggest): add custom tooltip 🍒 

---

CHANGELOG.md
package-lock.json
package.json
projects/angular/directives/ui-progress-button/src/internal/ui-button-progress-bar.component.scss
projects/angular/package.json
projects/playground/src/app/app-routing.module.ts
projects/playground/src/app/app.component.ts
projects/playground/src/app/pages/progress-button/progress-button.module.ts
projects/playground/src/app/pages/progress-button/progress-button.page.html
projects/playground/src/app/pages/progress-button/progress-button.page.scss
projects/playground/src/app/pages/progress-button/progress-button.page.ts

fix(progress-button): fix styling & add playground page

---

projects/angular/components/ui-suggest/src/ui-suggest.component.html
projects/angular/components/ui-suggest/src/ui-suggest.component.ts
projects/angular/components/ui-suggest/src/ui-suggest.mat-form-field.ts

Reduce the height of ui-suggest when no results are found and customItemSize is used.
https://uipath.atlassian.net/browse/OR-65722

fix(suggest): reduce height of ui-suggest when no results found

---

CHANGELOG.md
package-lock.json
package.json
projects/angular/components/ui-suggest/src/ui-suggest.component.ts
projects/angular/package.json

If the user selects previous entries while list is loading, the list would fail to load the resources.

fix(suggest): input clear for lazy loaded ui-suggest with multiple selection

---

CHANGELOG.md
package-lock.json
package.json
projects/angular/components/ui-suggest/src/ui-suggest.component.ts
projects/angular/package.json

With the MDC Components, the Checkbox inside a suggest's list option gets focused on click, making the input lose focus.
The behaviour is already ok if we try to select a new value, but if we search by an already selected value, deselect it by clicking on the checked Checkbox and then press ESC key, the dropdown is closed, the suggest input loses focus and the searched value is still there.
With this fix we'll clear the input and focus it after every selection/deselection.

fix: clear & focus suggest input on deselect

---

CHANGELOG.md
package-lock.json
package.json
projects/angular/components/ui-grid/src/components/ui-grid-custom-paginator/ui-grid-custom-paginator.component.html
projects/angular/components/ui-grid/src/components/ui-grid-custom-paginator/ui-grid-custom-paginator.component.scss
projects/angular/components/ui-grid/src/components/ui-grid-custom-paginator/ui-grid-custom-paginator.component.spec.ts
projects/angular/components/ui-grid/src/components/ui-grid-custom-paginator/ui-grid-custom-paginator.component.ts
projects/angular/components/ui-grid/src/models/dataModel.ts
projects/angular/components/ui-grid/src/ui-grid.component.html
projects/angular/components/ui-grid/src/ui-grid.component.ts
projects/angular/package.json
projects/playground/src/app/pages/grid/component/grid.component.html
projects/playground/src/app/pages/grid/grid.models.ts
projects/playground/src/app/pages/grid/grid.page.ts

Adds the option to have selectable page index.
It is an input on `ui-grid` for individual usage, and it's also added to the `GRID_OPTIONS` injectable token so it can be enabled across.
https://github.com/UiPath/angular-components/assets/9513641/c3586603-45fa-47ea-91f2-0009cee2394b

feat(grid): add selectable page index

---

CHANGELOG.md
package-lock.json
package.json
projects/angular/directives/ui-file-drop-zone/src/ui-file-drop-zone.directive.spec.ts
projects/angular/directives/ui-file-drop-zone/src/ui-file-drop-zone.directive.ts
projects/angular/package.json

- do not highlight drag area when dragging event does not contain Files
Before
After

fix(file-picker): dropzone should only highlight when dragging files

---

CHANGELOG.md
package-lock.json
package.json
projects/angular/components/ui-grid/src/_ui-grid-variables.scss
projects/angular/components/ui-grid/src/_ui-grid.theme.scss
projects/angular/components/ui-grid/src/filters/ui-grid-dropdown-filter.directive.ts
projects/angular/components/ui-grid/src/test/column.ts
projects/angular/components/ui-grid/src/ui-grid.component.html
projects/angular/components/ui-grid/src/ui-grid.component.scss
projects/angular/components/ui-grid/src/ui-grid.component.spec.ts
projects/angular/components/ui-grid/src/ui-grid.component.ts
projects/angular/components/ui-suggest/src/ui-suggest.component.ts
projects/angular/package.json

- fix translations for grid options when changing the lang
- add margin shadow to table and fade effect near the refresh button when grid is scrollable.  
Light theme:
Dark theme:

Fix: grid filter translations
